extends: 'airbnb-typescript/base'

parserOptions:
  sourceType: 'module'
  ecmaVersion: 2015
  project: './tsconfig.json'

env:
  es6: true
  browser: true

settings:
  import/resolver:
    alias:
      extensions: ['.ts']
      map:
        - ['~', './src']

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/prefer-default-export: off

