extends: 'airbnb-typescript/base'

parserOptions:
  sourceType: 'module'
  ecmaVersion: 2015
  project: './tsconfig.json'

env:
  es6: true
  browser: true

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  # implicit-arrow-linebreak: off

